name: CI
on:
  push

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [with-node, without-node]
        exclude:
          - os: windows-latest
            node: without-node
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        if: ${{ matrix.node == 'with-node' }}
      - name: Install Dependencies
        run: yarn install
      - name: Build Package
        run: yarn build
      - name: Run Action
        uses: ./
        with:
          firebase-token: 'banana'
      - name: Run Tests
        run: yarn test
